var attendee = sequelize.define('Attendee', {
    application-start: Sequelize.STRING,
    application-submit: Sequelize.STRING,
    name: Sequelize.STRING,
    email: Sequelize.STRING,
    gender: Sequelize.STRING,
    tshirt-size: Sequelize.STRING,
    diet-restriction: Sequelize.STRING,
    school: Sequelize.STRING,
    age: Sequelize.INTEGER,
    highschool-student: Sequelize.BOOLEAN,
    require-travel-reimbursement: Sequelize.BOOLEAN,
    first-hackathon: Sequelize.BOOLEAN,
    github-account: Sequelize.STRING,
    linkedin-account: Sequelize.STRING,
    personal-website: Sequelize.STRING,
    resume: Sequelize.BLOB,
    what-do-you-like-to-work-with: Sequelize.ARRAY(Sequelize.STRING),
})
